FROM golang:latest

# WORKDIR /app
# 依存ライブラリをダウンロードする(キャッシュを使いたいので、これを先にやる)
WORKDIR /go/src/app
ENV GO111MODULE=on
COPY go.mod go.sum ./
RUN go mod download

RUN go get github.com/gin-gonic/gin
RUN go get github.com/go-sql-driver/mysql
RUN go get github.com/jinzhu/gorm
RUN go get github.com/go-delve/delve/cmd/dlv
RUN go get go.uber.org/zap
RUN go get github.com/gin-contrib/cors
